language: python
python:
  - 3.4
  - 3.5
  - 3.6

install:
  - pip install -r requirements
  - pip install -e .

script:
  make doc

deploy:
  provider: pages
  skip_cleanup: true
  github_token: ${GH_TOKEN}
  local_dir: docs/_build/html
